# Site settings
title: Igor Rocha - Web Developer
email: igortice@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog Igor Rocha Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: igortice
github_username:  igortice

# Build settings
markdown: kramdown

exclude:
  - "Gruntfile.coffee"
  - "node_modules"
  - "package.json"
  - "bower_components"
  - "bower.json"
