# Site settings
title: Blog Igor Rocha
email: igortice@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog Igor Rocha Web Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: igortice
github_username:  igortice

# Build settings
markdown: kramdown
